name: Build
on: [ push, pull_request, workflow_dispatch ]
jobs:
  build:
    strategy:
      matrix:
        java: [
          17-ubuntu,
          21-ubuntu
        ]
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/openjdk/jdk:${{ matrix.java }}
      options: --user root
    steps:
      # https://github.com/nektos/act/issues/973
      - name: Install node
        if: ${{ env.ACT }}
        run: |
          apt update
          apt install -y curl git
          curl -fsSL https://deb.nodesource.com/setup_20.x | bash - 
          apt install -y nodejs
      - name: Install git on container
        if: ${{ !env.ACT }}
        run: |
          apt update
          apt install -y git
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - name: Create run_tests dir if non existent
        run: mkdir -p run_tests
      - uses: gradle/actions/wrapper-validation@v4
      - run: chmod +x ./gradlew
      - name: Build Porting-Lib
        run: chmod +x ./gradlew && ./gradlew build publishToMavenLocal
        working-directory: ./Porting-Lib
      - uses: actions/upload-artifact@v4
        if: ${{ !env.ACT && matrix.java == '21-ubuntu' }} # Only upload artifacts built from latest java
        with:
          name: Porting-Lib Artifacts
          path: /root/.m2/repository/
      - name: Build with Gradle
        run: ./gradlew check build publishToMavenLocal --stacktrace --warning-mode=fail -Porg.gradle.parallel.threads=4
      - name: Remove unnecessary build files and move necessary ones
        if: ${{ matrix.java == '21-ubuntu' }} # Only upload artifacts built from latest java
        run: |
          rm -rf build/libs/*
          cp **/build/libs/* build/libs
      - name: Capture build artifacts
        if: ${{ !env.ACT && matrix.java == '21-ubuntu' }} # Only upload artifacts built from latest java
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/
      - uses: actions/upload-artifact@v4
        if: ${{ !env.ACT && matrix.java == '21-ubuntu' }} # Only upload artifacts built from latest java
        with:
          name: Maven Local
          path: /root/.m2/repository
  check_resources:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/openjdk/jdk:21-ubuntu
      options: --user root
    steps:
      # https://github.com/nektos/act/issues/973
      - name: Install node
        if: ${{ env.ACT }}
        run: |
          apt update
          apt install -y curl git
          curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
          apt install -y nodejs
      - name: Install git on container
        if: ${{ !env.ACT }}
        run: |
          apt update
          apt install -y git
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - uses: gradle/actions/wrapper-validation@v4
      - run: chmod +x ./gradlew
      - name: Build Porting-Lib
        run: chmod +x ./gradlew && ./gradlew build publishToMavenLocal
        working-directory: ./Porting-Lib
      - name: Generate Resources
        run: ./gradlew generateResources --stacktrace --warning-mode=fail
      - run: if [ -n "$(git status --porcelain)" ]; then exit 1; fi